:PROPERTIES:
:ID:       d808fb6b-e537-491d-baa6-72ed39015a2e
:END:
#+title: Emails
* 05.02.2024
** DONE Email --> Prof. Hampel
CLOSED: [2024-02-26 Mon 10:28]

Sehr geehrter Prof. Hampel,

ich möchte mich für einen Urlaub zwischen diesem Zeitraum 26.03.2024-02.04.2024 beantragen, da es eine Konferenz von meiner Gemeinde gibt. Da es ist das erste Mal für mich, einen Urlaub zu beantragen, wusste ich nicht, dass ich mich im Voraus bei Ihnen bewerben musste und deshalb habe mein Flugticket schon gekauft. (Das nächste Mal werde ich darauf achten.)

Ich wäre sehr dankbar, wenn ich Ihre Zustimmung erhalten kann. :)

Mit freundlichen Grüßen
Guanghao Jiao
-----

* 26.02.2024
** DONE Email --> Frau Julia Nahler
CLOSED: [2024-02-26 Mon 10:28]

Sehr geehrte Frau Nahler,

ich habe gerade eine Frage zur Verlängerung eines Vertrags und möchte Sie fragen.

Der Grund ist so:

Ich muss bis Ende März ausziehen und ich bewerbe mich gerade an eine neue Wohnung. Aber meine gegenwärtiger Vertrag ist nur bis 25.09.2024. Das ist zu kurz und nicht möglich, einen Mietvertrag zu erfüllen. Meine Aufenthaltstitel ist im Prozesss der verlängerung und ich werde sie am 19.03.2024 bekommen. Aber das Problem ist, wenn ich nach 19.03.2024 beginne, meinen Arbeitsvertrag zu verlängern, es dauert lang und ich werde wahrscheinlich wohnungslos.

Deshalb möchte ich fragen, kann ich jetzt meinen Arbeitsvertrag verlängern (, bevor ich meine verlängerte Anufenthaltstitel bekommen habe)?

Bitte entschuldigen Sie die Komplexität meiner Frage. Ich freue mich auf Ihre Antwort und wünche Ihnen einen schönen Montag. :)

Mit freundlichen Grüßen
Guanghao Jiao

---Nach ---
Betreff: Anfrage zur Verlängerung meines Arbeitsvertrags aufgrund bevorstehendem Umzug

Sehr geehrte Frau Nahler,

ich hoffe, diese Nachricht erreicht Sie wohlauf. Ich bin Guanghao Jiao, Promotionsstudent an der TU-Dresden und beim HZDR tätig. Ich wende mich an Sie, da ich eine Frage zur Verlängerung meines Mietvertrags habe.
 
Der Hintergrund ist folgender:

Ich muss bis Ende März ausziehen und bewerbe mich derzeit um eine neue Wohnung. Allerdings läuft mein aktueller Mietvertrag nur bis zum 25.09.2024, was zu kurz ist, um einen neuen Mietvertrag abzuschließen. Mein Aufenthaltstitel befindet sich im Verlängerungsprozess, und ich werde ihn unbedingt am 19.03.2024 erhalten. Das Problem ist, wenn ich erst nach dem 19.03.2024 meinen Arbeitsvertrag verlängere, wird der Prozess zu lange dauern, und ich laufe Gefahr, obdachlos zu werden.

Daher möchte ich fragen: Ist es möglich, meinen Arbeitsvertrag bereits jetzt zu verlängern, bevor ich meinen verlängerten Aufenthaltstitel in Händen halte?

Ich bitte um Entschuldigung für die Komplexität meiner Anfrage. Ich freue mich auf Ihre Rückmeldung und wünsche Ihnen einen schönen Montag. :)

Mit freundlichen Grüßen
Guanghao Jiao

-----

** DONE Email --> Ausländerbehörde
CLOSED: [2024-02-26 Mon 10:29]

Sehr geehrte Frau Krömann,

ich werde meinen Aufenthaltstitel am 19.03.2024 erhalten und gerade ist er im Verlängerungsprozess. Allerdings würde ich gerne wissen, ob es möglich ist, ihn früher zu bekommen, oder zumindest zu wissen, bis zu welchem Datum mein Aufenthaltstitel verlängert wird.

Der Grund ist, ich muss meinen Arbeitsvertrag verlängern, da ich kurz ausziehen muss und gerade eine neue Wohnung suche. Aber der Arbeitsvertrag ist so kurz, dass ich keine Wohnung mieten kann. Um die Arbeitsvertrag zu verlängern, ich müsste aber den verlängerten Aufenthaltstitel bekommen, oder zumindest wissen, bis zu welchem Datum mein Aufenthaltstitel verlängert wird.

Wenn ich bis zum 19.03.2024 warte, um eine Verlängerung meines Arbeitsvertrags zu beantragen, er dauert lange und ich werde wahrscheinlich für eine lange Zeit wohnungslos.

Bitte entschuldigen Sie, dass ich Ihnen ein so komplexes Thema beschreibe. Ich freue mich auf Ihre Antwort und wünsche Ihnen einen schönen Montag. :)

Mit freundlichen Grüßen
Guanghao Jiao

* Emails --> Frau Nahler

Sehr geehrte Frau Nahler,

ich danke Ihnen sehr für Ihre schnelle Rückmeldung und Ihr Verständnis. Das formlose Schreiben wird sehr hilfreich sein, auch vielen Dank für die Herstellung dieses formlosen Schreibens.

Im Anhang ist ein Dokument des Abgabetermins (19.03.2024) von meinem eAT. Falls ich vor diesem Datum per E-Mail von der Ausländerbehörde einen schriftlichen Bescheid erhalte, werde ich sie Ihnen umgehend zusenden.
Danke und einen schönen Dienstag! :)

Mit freundlichen Grüßen
Guanghao Jiao
