:PROPERTIES:
:ID:       d1545417-7be7-40e4-84bd-76768e9f2d8f
:END:
#+title: Kick-off Meeting Presentation 2024-02-14
* Why Generation IV reactor? Why liquid metal cooled reactor?
** [[id:2469e339-c724-4f86-b520-00c64f850045][Nuclear Reactor Generation IV]]
1. Inherently safe
2. Retention of the fuel in the core
3. Higher operating temperature --> higher thermal efficiency
* Is it popular? Why it is not widely used?

* Which safety trajectories are used and which roll does the void effect play in those trajectories?

* How does the gas entrainment influence the nuclear safety?

* What is going to be investigated?

-----
* Presentation speech
The second page:

In the next slide, I would like to show you the motivation regarding the first problem in the sodium-cooled reactor.
At first, I want to introduce the void coefficient briefly to you.
The void coefficient describes the relationship between the reactivity and the void coefficient.
For most normal reactor, the void coefficient is negativ. That mean, there is a negative feedback between the void fraction and the reactivity.
However, most SFR has a positive void coefficient. This means, there is a positive feedback between the void fraction and the reactivity. And the safety concerns come from here.

However, in the normal conditions, this effect is safe. Even up to 50% of void, which is unpractical, the reactor is still safe.
But in the accident conditions, which is very very unlikely to happen, this positive void coefficient may lead to problems.

For exmaple there is an accident scenario.
If the coolant channel is somehow blocked, the liquid sodium may begin to boil. And the void fraction increases and this is a positive feedback. At the end the fuel rods may burn out. This is very very unlikely to happen.

Therefore, the positive coefficient leads to safety problems only at very very unlikely accidents.
In the normal condidions, there are different bubble scenarios, here are some exmaples.

When there are homogeneous small bubbles, the sodium density and the inelastic scattering effect decrease, as a result, the neutrons become harder and are more abundant. At the same time, the neutron leakage is few. Overall, the effect is an undesirable increase in void fraction.

For the condition of single bubble in the core, the effect is also an increase in the void fraction, but it is a local effect.

For the condition of a single bubble near the wall, the situation is different. Although there is a decrease in the sodium density and the inelastic scattering effect, there is much more neutron leakage. This leads to a decrease in the void coefficient.

There are also some behaviours. For example, collapse and coalescence. For a bubble with a diameter of 10 cm, the collapse peak pressure could be 8000 atm, but the released energy is very less. For coalescence, I need to read more literature.

And currently I just have very basic ideas about the experiments, for example, experiments at different flow rate, different bubble size. The bubbles can be released homogeneously or locally. Thank you for listening.
