:PROPERTIES:
:ID:       e60947d8-45d1-4668-b9ae-c16232c347b0
:END:
#+title: Heavy Water
Why heavy water is demanded by the contries in the war at the beginning of the nuclear experiment (several decades ago)?

Because at the beginning, for example, the first nuclear pile in human history, the moderator is made of graphite. However, the graphite is less efficient, and water is a very good moderator, due to its high content of hydrogen.

Nevertheless, the water as a moderator has a fatal disadvantage, that is, when water slows down the neutrons, it absorbs neutrons at the same time. A water molecule absorbs a neutron and becomes heavey water. his is because a hydrogen atom absorbs a neutron to be a deuterium $D$.

This adsorption leads to the waste of enriched Uranium. The scientists at that time want to overcome this disadvantage of water as moderator, so they just use the heavy water directly as moderator.

It is also interestion that Germany at the time of the world war II, it was unable to produce a nuclear bomb, due to the lacking of heavy water.

But how is the heavy water produced? See note [[id:1679c8d1-ef25-470d-9eed-be52cd1d34c7][Production of Heavy Water]].

