:PROPERTIES:
:ID:       d5888c70-4a5a-480c-ad02-6c64079a1700
:END:
#+title: Two-phase flow in SFR

This section is cited from [[id:54fcfb94-df84-44c8-a0be-9ea6eda7e15b][parsegianSeriesMonographsTextbooks]] (P. 168).
The [[id:fc0b7a37-58b1-4468-b51d-04b6df00fa2b][Two Phase Flow]] in SFR is one of the most important features in my research.
* Bubble Source
First, we should talk from the beginning, about how is the two-phase flow generated.

Actually, it has two main sources.
** Externally introduced gases
--> for more details see [[id:f5375015-9cd7-4bad-911c-463408a81a81][Voiding Effects]].
There are some ways to reduce the sodium void effect, for example, reducing the positive spectral shift effect and/or enhancing the negative leakage increase effect. (cite: [[id:09f78e9d-b76e-4dc7-83ab-7494eb161086][tommasiValidationSodiumVoid2010]])
** Vaporization of the coolant
This subsubsection is cited from [[id:8c84eafc-a7ec-4499-bd4c-eb0d3d416f96][schulenbergFourthGenerationNuclear2022]] (P. 100).

In normal operation, the sodium does not boil. It enters the core from below at about 400 Celcius and exits the top at about 550 Celcius. So there is a high safety margin between the operation temperature and the boiling temperature of 883 Celcius.

However, in some special scenarios, the sodium could still boil.
*** Scenario: Cooling Channel Blocked and Sodium Boiling
:PROPERTIES:
:ID:         f48cfc71-df88-45e4-b53d-e49347d2f29d
:NOTER_DOCUMENT: mylib/pdf/schulenbergFourthGenerationNuclear2022.pdf
:NOTER_PAGE: 111
:END:
#+BEGIN_QUOTE
Sodium boiling does not occur at normal operation. But just like the title said, when the cooling channel is blocked, sodium still could boil. Then the sodium vapor displaces the liquid sodium. Fewer neutrons are absorbed and the neutron flux increases. (In my opinion, this is actually due to the reduction of the [[id:ddd58597-7bde-43b4-a669-a7c24414ffd9][Inelastic Scattering]], so that the neutrons become harder, see [[id:acd31f8e-c8fd-4338-a1d4-5fb90aeb6662][Void Coefficient of Sodium]].) Due to the positive void coefficient, the temperature continues to rise. The [[id:9bf80bd9-f397-4de1-bcc8-21108c40f9be][Doppler Effect]] could hold this back, but it will be still too late, that the core may be already burned out.
cite: [[id:8c84eafc-a7ec-4499-bd4c-eb0d3d416f96][schulenbergFourthGenerationNuclear2022]] (P. 100).
#+END_QUOTE

But what happens to the [[id:fc0b7a37-58b1-4468-b51d-04b6df00fa2b][Two Phase Flow]] in this scenario? Do the bubbles (sodium vapor) coalesce with each other?

**** Accident Scenario SFR
:PROPERTIES:
:NOTER_PAGE: 110
:END:
#+BEGIN_QUOTE
In normal operation, the sodium does not boil. It enters the core from below at approx. 400 °C and exits at the top at approx. 550 °C on average. So we still have a high safety margin compared to the boiling temperature. However, if cooling channels become blocked, it could still boil. Then the sodium vapor displaces the liquid sodium, fewer neutrons are absorbed, and the neutron flux increases. That’s a positive void effect, and that’s bad. If the reactor got hot enough somewhere to boil the sodium, it would get then even hotter because of this effect. Again, the Doppler effect will control the power back, but the fuel rod may have already burned out by then.
#+END_QUOTE

**** Specificities of SFR
:PROPERTIES:
:NOTER_PAGE: 111
:END:
#+BEGIN_QUOTE
One can see from this discussion that a fast reactor is in many ways more sophisticated than a pressurized or boiling water reactor. The fast reactor has a much higher neutron flux, a weaker Doppler effect, a positive void effect, and a smaller fraction of delayed neutrons. In addition, sodium can burn when it leaks.
#+END_QUOTE
* Generals
Any bubbles are dispersed by inlet plenum flows rather than concentrated at a single point.

It is most unlikely that the externally introduced bubbles could have a serious reactivity effect. But the very small bubbles will penetrate to the core and their effects on the heat transfer should be considered.

--> Focus on the heat transfer:
* Effects on the heat transfer
For homogeneous small bubbles, even if the void fraction is up to 50%, there will be unlikely failures. And this void fraction is not practical.

For the big bubbles, there will also be unlikely failures, but they may insult some fuel pins.
