:PROPERTIES:
:ID:       bda2bd57-6f11-4b5b-9490-398f7b78fbd7
:END:
#+title: Learning from Phénix (SFR)

The Phénix (SFR) has already shut down. There are many things we can learn from it.

- The first thing is the economic feature. We should not forget it.
- Also, the [[id:f5375015-9cd7-4bad-911c-463408a81a81][Voiding Effects]] needs to be reduced.
- The [[id:9bf80bd9-f397-4de1-bcc8-21108c40f9be][Doppler Effect]] should be increased.
- The loss of reactivity during the operation should be minimized.


#+begin_quote
- Reduction of the sodium void effect. The void coefficient in fast neutron reactors is positive, which means that reactivity increases if loss of sodium coolant occurs by boiling or gas intrusion.
#+end_quote
--> To reduce the void coefficient is very important.

#+begin_quote
Therefore the sodium void effect of the core of the prototype must be of the same magnitude as the one of the commercial reactor, Camercat explained. For a core with height to diameter ratio of 0.25, a small core reactor (~2.6m3) will have a void coefficient of the order of 500 pcm (1 pcm is a thousandth of a percent) and that a large core reactor (15.5m3) will have a void coefficient of the order of 1300 pcm. In the case of an Unprotected Loss of Fluid Accident (ULOF), the small core can be stabilized by the prompt temperature coefficient due to the Doppler effect. But the larger core will not be, inducing early in the transient a power increase and a significant energy release. Therefore, to keep the same behavior when going from prototype to commercial reactor, a larger core volume (at least 5.2m3) must be retained at the prototype scale to be able to extrapolate the safety analysis to the commercial scale.
#+end_quote
--> Although the ratio is the same, the scale is a problem.
  cite: [[https://www.neimagazine.com/features/featurelearning-from-ph-nix/][Learning from Phénix]]
