:PROPERTIES:
:ID:       bf8af33d-30a9-40e1-b8fe-39f76fd281f1
:END:
#+title: RIMANUS Meeting 20240308
* Preparation
Talk about:

- the background
- my motivation --> safety
- how many different kinds of bubbles are there in the reactor --> during which kinds of scenarios?
- how people can benefit from my work --> CFD people

There are different kinds of bubbles in the SFR.

- Argon bubbles
- fuel bubbles
- Sodium bubbles

The [[id:8fc68ce9-87c2-45c7-9542-87c6c6139fbc][Core Disruptive Accident (CDA)]] happens only in extremely impossible hypothetic scenarios.
-----
The blockage of coolant and sodium boiling is one typical scenario. In this scenario, the positive void coefficient leads to positive feedback between the void fraction and the reactivity. Thus CDA may happen. This safety issue is closely related to the study on the two-phase flow in liquid metal.

However, this aspect is not well-researched.

Nowadays, we have the fastest X-ray tomography setup with high resolution, and a range of experiments are to be planned and operated. The following questions are to be answered:

1. To what extent would the experiments without flow velocity represent the real condition in the SFR? (Is a pump necessary for the experiment?)
2. How does the argon bubble swarm behave when freely rising?
   - collapse
   - coalescence
3. How does the argon bubble swarm behave in the core of the SFR (under the influence of the assembly)?
4. How do sodium bubble behaviors differ from water bubbles?

The purpose of the experiment is to provide the researchers with a benchmark database to establish the models, for example, CFD models, and have a better option to simulate the accident scenarios more precisely, to help improve the safety level of SFR.

At the end, the bubble parameters from different models would be collected and compared.
* Contents
- I showed the 1-slide presentation.
  + I need to modify my presentation.
- It was mainly about the conferences.
- There were several questions that I needed to figure out.
  + 

