:PROPERTIES:
:ID:       f8ed4d51-6490-4ba0-944b-7abe29a8f5d8
:END:
#+title: Sodium-Cooled Fast Reactor (SFR)
* Features
The SFR is actually very flexible. The [[id:bbcd0b65-0628-478d-8f50-8ba1affef81a][Conversion Ratio]] of the reactor can be adjusted.

* Void Coefficient of Sodium
:PROPERTIES:
:ID:       acd31f8e-c8fd-4338-a1d4-5fb90aeb6662
:END:
Different from the normal reactors, for [[id:f8ed4d51-6490-4ba0-944b-7abe29a8f5d8][Sodium-Cooled Fast Reactor (SFR)]], the void coefficient is actually complex. Mostly, the void coefficient is positive. But there are also exceptions, e.g. Toshiba Corp. reactor concept 4S, the void coefficient is clearly negative, cite: [[id:8c84eafc-a7ec-4499-bd4c-eb0d3d416f96][schulenbergFourthGenerationNuclear2022]] (P. 109).

There are two trade-off effects.

Firstly, sodium doesn't moderate neutrons by absorbing neutrons. However, sodium interacts with neutrons by scattering.

For the high-energy neutrons, they interact with the sodium nucleus by [[id:ddd58597-7bde-43b4-a669-a7c24414ffd9][Inelastic Scattering]], which means this is an endothermal reaction. For the low-energy neutrons, they interact with the sodium nucleus by [[id:d59ea60c-97a5-4ec9-a5c4-fd831a1a3ba8][Elastic Scattering]]. Therefore, when the sodium void fraction increases, the sodium density decreases. Then, the neutrons with high energy can not be well removed. Thus, the neutrons become "harder" and thus more energetic. Actually, neutrons at higher energy will produce more neutrons during the fission reaction. (This is indicated by $\eta$, which equals the emitted neutrons per inducing neutron in the fission. $\eta$ must be higher than 1 to reach the critical reaction of the fission, and Uranium is the only natural [[id:436fb988-ea1e-42b5-80b4-dedec97d7578][Fissile Material]], of which $\eta>1$.) This effect tends to lead to the void coefficient being positive.

Secondly, the increase in the void fraction leads on the other hand to the neutron leakage. This means the fuel receives less neutrons. This effect tends to lead to the void coefficient negative. 

Nevertheless, the neutron leakage is highly dependent on the location of the void. Void in the core: (almost) no leakage. Void around the wall: leakage --> negative void coefficient.

All in all, the void efficiency of the sodium is complex and needs to be investigated based on different situations. A negative coefficient is needed, but apparently, it is not easily guaranteed as negative.

This section is cited from [[id:405b8de2-8c46-4b27-a5de-137a3455a428][lamarshIntroductionNuclearEngineering2001]] (P. 375)

* [[id:d5888c70-4a5a-480c-ad02-6c64079a1700][Two-phase flow in SFR]]





