:PROPERTIES:
:ID:       3d473d21-5ba7-40f2-a5b8-84cc6c46a920
:END:
#+title: Bubble Coalescence
* (Water) [[id:6d7a63dd-dfbf-48f8-b836-f50728e0112c][Surface Tension]] $\uparrow$ Coalescence $\downarrow$
#+begin_quote
In coalescing liquids such as pure water, a large fraction of bubble collisions results in the formation of bigger bubbles. In contrast, in noncoalescing liquids, colliding bubbles tend to bounce off each other due to surface tension effects and do not coalesce readily. ([[id:07a9e2ee-ab9d-4846-862e-bd06c9ea5b59][doranBioprocessEngineeringPrinciples2013]], [[https://www.sciencedirect.com/topics/engineering/bubble-coalescence][Sciencedirect: Bubble Coalescence]])
#+end_quote

* (Water) [[id:d53a8258-947c-4496-9624-7c475d5bbcb8][Viscosity]] $\uparrow$ Coalescence $\uparrow$, [[id:6d7a63dd-dfbf-48f8-b836-f50728e0112c][Surface Tension]] $\uparrow$ Coalescence $\downarrow$
#+begin_quote
The effects of liquid viscosity and surface tension on the coalescence have been investigated. It has been found that the interaction between the leading and following bubbles depends mainly on the liquid viscosity. The higher the liquid viscosity, the easier the bubbles interact. Therefore, bubble coalescence is more likely for high viscosity. On the other hand, for low viscosity, the liquid jet behind the leading bubble becomes stronger which prevent the bubble interaction. A postponed or non-coalescence is obtained. Regarding the surface tension effect, high surface tension results in a weak liquid jet, and the resultant high surface tension force prohibits the surface stretching. Therefore, a late coalescence is obtained. ([[id:a77b5d48-82ae-4050-8ce0-64f20a099fdc][chenCOALESCENCEBUBBLESNUMERICAL]])
#+end_quote

* Collision $\uparrow$ Coalescence $\uparrow$
#+begin_quote
The coalescence rate is primarily determined by the collision frequency of the bubbles. Collision is evoked by turbulent fluctuations or velocity gradients in the fluid, different bubble velocities, bubble capture in eddies, or bubble wake interaction.
([[id:458876ec-83c2-4b8d-a4a7-e6b487f21046][haasReviewBubbleDynamics2021]])
#+end_quote
