:PROPERTIES:
:ID:       b24dde29-0d3f-4fc5-8a60-1d2f14d0b391
:END:
#+title: Report: One or Two Pages of the Motivation
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+date: <2024-02-28 Wed>
#+author:Guanghao Jiao
#+email: jiao73@hzdr.de
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 29.2 (Org mode 9.6.15)
#+cite_export:
#+latex_compiler: auctex

* Introduction
In 1951, the first breeder reactor was built. In the 1960s and 1970s, several SFRs were built. However, due to reasons for example some accidents in SFRs, the success of the LWRs, and the illusion of adequate fuel, the development of the SFRs was stopped since the late 1980s.

In the 21st century, with the ongoing global warming and the increase in the [[id:16df8af2-39a6-4b07-934b-0598b0ec0a9f][radioactive waste]] produced by the LWRs, the R&D on the [[id:2469e339-c724-4f86-b520-00c64f850045][generation IV nuclear reactors]] reemerged, aiming at the development of revolutionary reactors with inherent safety features, efficient utilization of the fuel and better management of the radioactive waste. Among them, the sodium-cooled fast reactor (SFR) is the most promising one, due to its long operation experience and excellent thermal-physics performance of sodium.

\cite{TechnologyRoadmapUpdate}

[[id:b9287555-daaf-4812-b2ff-fa64812cd568][\cite{zuoTwodimensionalNumericalSimulation2013}]]

\bibliographystyle{plain}
[[bibliography:c:/Users/j8154/AppData/Roaming/org/mylib/bib/mylib.bib]]
