:PROPERTIES:
:ID:       5774c7fb-4116-4788-9ad6-8772997a0399
:END:
#+title: Wave–particle Duality
In the initial [[id:0227e5e3-09a6-4ee5-bf71-2c3c507bf2d7][Double-slit Experiment]], scientists discovered that photons interfered with each other and concluded that light was a wave.

But in the [[id:1177104c-7e3b-45e6-b83e-f21f5cb9961e][Photoelectric Effect]] experiment, when they hit a metal surface with a beam of light, a spark was produced.

According to the [[id:e2792f1c-dcde-4e28-9443-b8a43214b3bc][Wave Model]], the increase of the intensity of the beam would lead to the increase of the emission electrons.

However, the quantity of the emission electrons had nothing to do with the intensity but is only related to the frequency of the beam.

More significantly, only when the frequency higher than a threshold value, the electrons can be emitted.

This phenomenon brought doubt to the scientists, because what the experiments results told them was that photons are particles!

The [[id:2f32fc5f-2673-4253-a626-13e767444fa1][Quantum Mechanics]] is established inspired by this phenomenon. And the wave-particle duality is discoverd in this way.

Einstein then come up with this formula: $E = h \cdot \gamma$. $h$ is Planck constant, $\gamma$ is the frequency.

There is a very basic law that the frequency is inversely proportional to wavelength: $c = \lambda \cdot \gamma$.

By the [[id:8b843821-0766-40f8-b863-ffe7c009c22d][Planck–Einstein Relation]] ($E = h \cdot \gamma = \frac{hc}{\lambda}$), the wave theory and the partical theory is related to each other.


------
Actually it depends on the scale of the particle, which model (wave or particle) to use.

small --> particle

big --> wave

The rest mass of a photon is 0. Because of the [[id:283726cc-4f4e-483d-b8c8-9c668c373409][Theory of Relativity]], the photon has momentum.

Whether a photon is more like a wave or a particle, is related to his scale.
