:PROPERTIES:
:ID:       648bb94d-f3af-4d8b-a010-75fd844621e2
:END:
#+title: 2024-02-27
#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_engraved_theme:
#+latex_compiler: pdflatex
#+date: \today

* Introduction
The study of liquid sodium reactor begins at 1960s. From 1960s to 1970s, the research on SFR is mainly focused on the military research. After that, the SFR has come to the citizen utilization.

During XX and XX, the research on the SFR is stopped.
The reasons are mainly:
 1. XXXXX. The most SFRs are in the state of shutdown.
 2. 
 3. 

However, on the wave of GIF, the R&D for the Gen. IV reactors is planed and the SFR comes into our view again. Among all of the reactors, the sodium reactor is the most promised one.

Because it has such advantages:
 1. There is plenty of operation experience.
 2.
 3.

But these disadvantages need to be overcomed:
 1.
 2.
 3.

* Motivation
One of the main aim of R&D of the Gen. IV reactors is the satety of the reactors. The positive void effect of SFR is one of the safety problems. The increase of the void fraction leads to the increase in reactivity. Although it only lead to safety problems at very rare (almost impossible) accident, it is still posibble. Additionally, it reduces the efficiency of the usage of the fuel.

To solve this problem, on the one hand, researchers has spend much effort on the design of the reactor structure to reduce the sodium void effet (coefficient). (For example, strategies: 1, 2, 3.) Toshiba has already invented a kind of the modular SFR reactor, see XX. On the other hand, researchers are working on the study on the two phase flow in liquid metal. Because, the void coefficient is dependent not only on the structure, but also the bubble behaviours in the reactor. For example, the CFD simulation is based on both of the understanding on the to phase flow behaviours in the liquid metal and the structure of the reactor. The two are linked as a whole.

Based on this background, the study on the liquid metal begins.

* Essentials
The void effect is defined as:
                    XX
The void effect of most normal reactors, e.g. XX and XX, is negativ. The increase in the void fraction leads to the reduction in the reactivity, resulting in a self-prevent effect and this is stable.

Howerver the void coefficient of SFR is positive and this is instable and more complex.

The sodium void effect is mainly dependent on the two trade-off effects: neutron moderation and neutron leackage.

** Neutron Moderation
Liquid sodium works not only mainly as coolant but also partially as moderator.
- neutron cross-section
- inelastic scattering at high energy
** Neutron Leackage
- Locally, this is dependent on where does the bubble stay.
- Homogeneously, this is dependent on the structure of the reactor --> the volume ratio of liquid sodium and fuel rod. 

* Experiment Plan
According to the explain in the Essential section, these questions are important:

- Why study Na, not water?
  + Because the surface tension is different so that we assume the bubble shapes are different in Na and water.
- Will or how do bubbles coalescence and collapse?
- Will bubbles enter the core or just rise outside the core?
- If they enter the core, will they stay in the core or will they go through the core?
